-- ============================================================
-- MemoLingua · 核心 Schema 遷移
-- VARK 三源融合 + FSRS 記憶 + EEG 腦波
--
-- 用法：Supabase → SQL Editor → 貼上整段執行一次。
-- 安全：可重複執行（IF NOT EXISTS / CREATE OR REPLACE / DROP POLICY IF EXISTS）。
-- 前提：auth.users 與 conversations 已存在（本專案已有）。
-- 跑完後再跑 seed_vark_questions.sql 匯入題庫。
-- ============================================================

-- ---------- 1. vark_questions（題庫，公開可讀） ----------
CREATE TABLE IF NOT EXISTS public.vark_questions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text text NOT NULL,
  context       text,
  option_v      text NOT NULL,
  option_a      text NOT NULL,
  option_r      text NOT NULL,
  option_k      text NOT NULL,
  category      text,
  language      text NOT NULL DEFAULT 'zh',
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------- 2. vark_responses（測驗作答） ----------
CREATE TABLE IF NOT EXISTS public.vark_responses (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  question_id   integer REFERENCES public.vark_questions(id) ON DELETE SET NULL,
  selected_type text NOT NULL CHECK (selected_type IN ('visual','auditory','reading','kinesthetic')),
  session_id    uuid NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vark_responses_session ON public.vark_responses(session_id);
CREATE INDEX IF NOT EXISTS idx_vark_responses_user ON public.vark_responses(user_id);

-- ---------- 3. vark_profiles（三源融合輪廓，每人一列） ----------
CREATE TABLE IF NOT EXISTS public.vark_profiles (
  user_id            uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  quiz_v numeric NOT NULL DEFAULT 0, quiz_a numeric NOT NULL DEFAULT 0,
  quiz_r numeric NOT NULL DEFAULT 0, quiz_k numeric NOT NULL DEFAULT 0,
  behavior_v numeric NOT NULL DEFAULT 0, behavior_a numeric NOT NULL DEFAULT 0,
  behavior_r numeric NOT NULL DEFAULT 0, behavior_k numeric NOT NULL DEFAULT 0,
  eeg_v numeric NOT NULL DEFAULT 0, eeg_a numeric NOT NULL DEFAULT 0,
  eeg_r numeric NOT NULL DEFAULT 0, eeg_k numeric NOT NULL DEFAULT 0,
  blended_v numeric NOT NULL DEFAULT 0, blended_a numeric NOT NULL DEFAULT 0,
  blended_r numeric NOT NULL DEFAULT 0, blended_k numeric NOT NULL DEFAULT 0,
  dominant_type      text,
  confidence         numeric,
  conversation_count integer NOT NULL DEFAULT 0,
  avg_cognitive_load numeric,
  best_learning_hour integer,
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- ---------- 4. eeg_sessions（腦波匯總） ----------
CREATE TABLE IF NOT EXISTS public.eeg_sessions (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  conversation_id  uuid,
  device           text,
  duration_sec     numeric,
  delta numeric, theta numeric, alpha numeric, beta numeric, gamma numeric,
  engagement       numeric,
  cognitive_load   numeric,
  encoding_strength numeric,
  relaxation       numeric,
  eeg_v numeric, eeg_a numeric, eeg_r numeric, eeg_k numeric,
  signal_quality   numeric,
  recorded_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_eeg_sessions_user_time ON public.eeg_sessions(user_id, recorded_at DESC);

-- ---------- 5. memory_items（FSRS 記憶卡） ----------
CREATE TABLE IF NOT EXISTS public.memory_items (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content          text NOT NULL,
  meaning          text,
  encoding_context text,           -- visual / auditory / reading / kinesthetic
  fsrs_stability   numeric NOT NULL DEFAULT 0,
  fsrs_difficulty  numeric NOT NULL DEFAULT 0,
  fsrs_state       text NOT NULL DEFAULT 'new',
  lapses           integer NOT NULL DEFAULT 0,
  repetitions      integer NOT NULL DEFAULT 0,
  next_review_at   timestamptz NOT NULL DEFAULT now(),
  last_reviewed_at timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_memory_items_due ON public.memory_items(user_id, next_review_at);

-- ---------- 6. memory_reviews（複習紀錄） ----------
CREATE TABLE IF NOT EXISTS public.memory_reviews (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  memory_item_id  uuid NOT NULL REFERENCES public.memory_items(id) ON DELETE CASCADE,
  user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  quality         integer NOT NULL CHECK (quality BETWEEN 1 AND 4),
  review_modality text,
  eeg_engagement  numeric,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- RLS：每位使用者只能存取自己的資料；題庫公開可讀。
-- （server 端 API 用 service_role，會自動繞過 RLS。）
-- ============================================================
ALTER TABLE public.vark_questions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vark_responses  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vark_profiles   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eeg_sessions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_items    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memory_reviews  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS vark_questions_read ON public.vark_questions;
CREATE POLICY vark_questions_read ON public.vark_questions
  FOR SELECT USING (true);

DROP POLICY IF EXISTS vark_responses_own ON public.vark_responses;
CREATE POLICY vark_responses_own ON public.vark_responses
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS vark_profiles_own ON public.vark_profiles;
CREATE POLICY vark_profiles_own ON public.vark_profiles
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS eeg_sessions_own ON public.eeg_sessions;
CREATE POLICY eeg_sessions_own ON public.eeg_sessions
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS memory_items_own ON public.memory_items;
CREATE POLICY memory_items_own ON public.memory_items
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS memory_reviews_own ON public.memory_reviews;
CREATE POLICY memory_reviews_own ON public.memory_reviews
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- RPC：三源融合（SECURITY DEFINER 以便寫入 vark_profiles）
-- 權重：quiz 30% + behavior 40% + eeg 30%；缺的來源自動重新分配權重。
-- ============================================================
CREATE OR REPLACE FUNCTION public.refresh_vark_profile(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  p public.vark_profiles%ROWTYPE;
  qs numeric; bs numeric; es numeric;       -- 各來源總和
  wq numeric := 0; wb numeric := 0; we numeric := 0; wtot numeric;
  fv numeric; fa numeric; fr numeric; fk numeric;  -- 各型融合分數
  nsrc int := 0;
  bestval numeric; besttype text;
BEGIN
  SELECT * INTO p FROM public.vark_profiles WHERE user_id = p_user_id;
  IF NOT FOUND THEN RETURN; END IF;

  qs := p.quiz_v + p.quiz_a + p.quiz_r + p.quiz_k;
  bs := p.behavior_v + p.behavior_a + p.behavior_r + p.behavior_k;
  es := p.eeg_v + p.eeg_a + p.eeg_r + p.eeg_k;

  IF qs > 0 THEN wq := 0.30; nsrc := nsrc + 1; END IF;
  IF bs > 0 THEN wb := 0.40; nsrc := nsrc + 1; END IF;
  IF es > 0 THEN we := 0.30; nsrc := nsrc + 1; END IF;
  wtot := wq + wb + we;

  IF wtot = 0 THEN
    -- 完全無資料：平均
    fv := 0.25; fa := 0.25; fr := 0.25; fk := 0.25;
  ELSE
    fv := (CASE WHEN qs>0 THEN wq*p.quiz_v/qs ELSE 0 END
         + CASE WHEN bs>0 THEN wb*p.behavior_v/bs ELSE 0 END
         + CASE WHEN es>0 THEN we*p.eeg_v/es ELSE 0 END) / wtot;
    fa := (CASE WHEN qs>0 THEN wq*p.quiz_a/qs ELSE 0 END
         + CASE WHEN bs>0 THEN wb*p.behavior_a/bs ELSE 0 END
         + CASE WHEN es>0 THEN we*p.eeg_a/es ELSE 0 END) / wtot;
    fr := (CASE WHEN qs>0 THEN wq*p.quiz_r/qs ELSE 0 END
         + CASE WHEN bs>0 THEN wb*p.behavior_r/bs ELSE 0 END
         + CASE WHEN es>0 THEN we*p.eeg_r/es ELSE 0 END) / wtot;
    fk := (CASE WHEN qs>0 THEN wq*p.quiz_k/qs ELSE 0 END
         + CASE WHEN bs>0 THEN wb*p.behavior_k/bs ELSE 0 END
         + CASE WHEN es>0 THEN we*p.eeg_k/es ELSE 0 END) / wtot;
  END IF;

  -- 主型 = 最大值
  bestval := fv; besttype := 'visual';
  IF fa > bestval THEN bestval := fa; besttype := 'auditory'; END IF;
  IF fr > bestval THEN bestval := fr; besttype := 'reading'; END IF;
  IF fk > bestval THEN bestval := fk; besttype := 'kinesthetic'; END IF;

  UPDATE public.vark_profiles SET
    blended_v = round(fv*100, 2), blended_a = round(fa*100, 2),
    blended_r = round(fr*100, 2), blended_k = round(fk*100, 2),
    dominant_type = besttype,
    confidence = least(0.95, 0.16 + 0.24*nsrc),   -- 2源≈0.64、3源≈0.88
    updated_at = now()
  WHERE user_id = p_user_id;
END;
$$;

-- 測驗結束 → 統計該 session 作答為 quiz_*，upsert 後重算融合。
CREATE OR REPLACE FUNCTION public.calculate_vark_quiz(p_session_id uuid, p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE cv int; ca int; cr int; ck int;
BEGIN
  SELECT
    count(*) FILTER (WHERE selected_type='visual'),
    count(*) FILTER (WHERE selected_type='auditory'),
    count(*) FILTER (WHERE selected_type='reading'),
    count(*) FILTER (WHERE selected_type='kinesthetic')
  INTO cv, ca, cr, ck
  FROM public.vark_responses
  WHERE session_id = p_session_id AND user_id = p_user_id;

  INSERT INTO public.vark_profiles (user_id, quiz_v, quiz_a, quiz_r, quiz_k)
  VALUES (p_user_id, cv, ca, cr, ck)
  ON CONFLICT (user_id) DO UPDATE
    SET quiz_v = EXCLUDED.quiz_v, quiz_a = EXCLUDED.quiz_a,
        quiz_r = EXCLUDED.quiz_r, quiz_k = EXCLUDED.quiz_k,
        updated_at = now();

  PERFORM public.refresh_vark_profile(p_user_id);
END;
$$;

-- 由近 7 天 EEG 找出平均專注度最高的時段。
CREATE OR REPLACE FUNCTION public.compute_best_learning_hour(p_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE best_hour int;
BEGIN
  SELECT EXTRACT(HOUR FROM recorded_at)::int INTO best_hour
  FROM public.eeg_sessions
  WHERE user_id = p_user_id
    AND recorded_at >= now() - interval '7 days'
    AND engagement IS NOT NULL
  GROUP BY 1
  ORDER BY avg(engagement) DESC
  LIMIT 1;

  IF best_hour IS NOT NULL THEN
    UPDATE public.vark_profiles SET best_learning_hour = best_hour, updated_at = now()
    WHERE user_id = p_user_id;
  END IF;
END;
$$;

GRANT EXECUTE ON FUNCTION public.refresh_vark_profile(uuid)        TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.calculate_vark_quiz(uuid, uuid)   TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.compute_best_learning_hour(uuid)  TO authenticated, service_role;

-- ============================================================
-- 完成。接著跑 seed_vark_questions.sql 匯入題庫。
-- ============================================================
