-- ============================================================
-- MemoLingua · VARK 題庫 Seed（中文 16 + 英文 16）
-- 用法：Supabase SQL Editor 貼上執行（需先建好 vark_questions 表）
-- 可重複執行：先清空再插入
-- ============================================================
TRUNCATE TABLE public.vark_questions RESTART IDENTITY CASCADE;

-- ---------- 中文 16 題 ----------
INSERT INTO public.vark_questions
  (question_text, context, option_v, option_a, option_r, option_k, category, language)
VALUES
('你在學習一個新的英文文法規則時，最喜歡哪種方式？','例如：學習現在完成式',
 '看圖表或時間軸，了解「完成」的概念','聽老師用例句說明，跟著念出來',
 '閱讀文法書上的規則說明與例句列表','直接在對話情境中使用，邊說邊體會','學習','zh'),
('你在背新單字時，最有效的方法是什麼？',NULL,
 '用顏色標記或畫心智圖，將單字視覺化','大聲朗讀、用手機錄音反覆聽',
 '寫下單字、例句與中文解釋整理成筆記','用這個單字在真實對話中造句練習','記憶','zh'),
('你覺得哪種練習方式讓你說英文進步最快？',NULL,
 '看圖說話或觀察情境圖後描述','跟 AI 或母語者直接對話、即時互動',
 '先寫下稿子，讀完後再開口說','模擬真實場景，例如點餐、購物、面試','口說','zh'),
('當你遇到聽不懂的英文對話時，你通常怎麼做？',NULL,
 '重看畫面或字幕，觀察說話者的表情動作','反覆聆聽，注意語調和發音',
 '查閱逐字稿或字典，一字一句確認意思','根據情境猜測意思，直接試著回應看看','聽力','zh'),
('當你要解釋一件複雜的事情給朋友聽，你會怎麼做？',NULL,
 '畫圖、畫流程或用手勢比出結構','直接口頭說明，邊說邊確認對方理解',
 '寫下重點條列，讓對方看著說明','舉一個真實生活的例子來比喻','溝通','zh'),
('你最容易記住哪種類型的英文內容？',NULL,
 '有圖片配合的影片或簡報','有人對你說過的話、Podcast 或廣播',
 '你自己讀過並做筆記的文章','你親身參與過的對話或情境','記憶','zh'),
('你在準備一個英文報告時，第一步通常是什麼？',NULL,
 '規劃版面、畫草稿、找配圖','先對自己大聲說一遍，看看邏輯通不通',
 '查資料、列大綱、寫出完整文稿','想像自己在台上說話的情境，模擬練習','表達','zh'),
('學英文時，哪種回饋對你最有幫助？',NULL,
 'AI 標出你哪裡說錯，用顏色或圖示呈現','直接告訴你哪個地方發音或語調不對',
 '提供詳細的文字修正與建議說明','給你一個修正後的情境，讓你重新練一次','回饋','zh'),
('你在旅行中迷路，需要問路，你會怎麼準備？','假設你在一個英語系國家',
 '先在地圖上確認路線，準備好視覺參考','在心裡練習一遍要說的話，想好怎麼開口',
 '在手機上查好問路的英文句子，準備好念','直接走過去問，用肢體語言輔助溝通','情境','zh'),
('你參加一個英文課程，哪種上課方式讓你最投入？',NULL,
 '有豐富的投影片、影片和視覺教材','老師講解生動，有大量師生問答互動',
 '有講義、閱讀材料和詳細板書','小組活動、角色扮演或模擬任務','學習環境','zh'),
('你想學會在英文會議中表達意見，你會怎麼練習？',NULL,
 '找到真實會議的影片，觀察別人怎麼開口','找人模擬對話，練習即興表達',
 '閱讀「如何在英文會議發言」的指南文章','加入模擬會議或英文讀書會，實際操作','職場','zh'),
('你在學習英文時，感到最有成就感的時刻是？',NULL,
 '看懂一部沒有字幕的英文影片','和外國人順暢地聊了一段對話',
 '讀完一篇英文文章並完全理解','在真實場合成功用英文完成一件事','動機','zh'),
('你最喜歡哪種英文練習 App 的功能？',NULL,
 '有動態圖卡、情境圖片和視覺化進度','可以跟 AI 即時語音對話',
 '有詳細的文法解析和學習筆記功能','有任務挑戰、模擬情境和成就系統','工具偏好','zh'),
('你在學一個英文口音或腔調時，怎麼做最有效？',NULL,
 '看說話者的嘴形和臉部動作影片','反覆跟著音檔模仿，聽自己的錄音',
 '閱讀音標說明，了解發音規則','在真實對話中模仿使用，邊說邊調整','發音','zh'),
('你最喜歡哪種學習進度呈現方式？',NULL,
 '圖表、雷達圖或視覺化進度儀表板','語音播報你本週的學習摘要',
 '詳細的文字報告，列出強弱項分析','看到自己完成了哪些任務和挑戰','回饋','zh'),
('如果你只能選一種方式來複習這週學的英文，你選哪個？',NULL,
 '重看本週的圖卡和情境截圖','重聽本週的對話錄音',
 '重讀本週的文字筆記與對話紀錄','再做一次類似的情境對話練習','複習','zh');

-- ---------- 英文 16 題 ----------
INSERT INTO public.vark_questions
  (question_text, context, option_v, option_a, option_r, option_k, category, language)
VALUES
('When learning a new grammar rule, what works best for you?','e.g. the present perfect tense',
 'Looking at a timeline or diagram','Listening to the teacher explain with examples',
 'Reading the rules and a list of example sentences','Using it directly in a conversation','learning','en'),
('How do you best remember new vocabulary?',NULL,
 'Color-coding words or drawing a mind map','Saying words out loud and recording yourself',
 'Writing down the word, definition and examples','Using the word in a real conversation','memory','en'),
('Which speaking practice helps you improve most?',NULL,
 'Describing pictures or situations','Real-time conversation with AI or a native speaker',
 'Writing a script first, then reading it aloud','Role-playing realistic scenarios','speaking','en'),
('When you don''t understand a conversation, what do you do?',NULL,
 'Replay the video and watch body language','Listen again, focusing on tone and rhythm',
 'Look up a transcript word by word','Guess from context and try to respond','listening','en'),
('Explaining something complex to a friend, you tend to:',NULL,
 'Draw a diagram or use gestures','Just talk it through and check they follow',
 'Write down key points as a list','Give a real-life analogy','communication','en'),
('Which type of content do you remember most easily?',NULL,
 'Videos or slides with strong visuals','A podcast or something someone told you',
 'Articles you read and took notes on','Conversations you personally went through','memory','en'),
('Preparing a presentation, what do you do first?',NULL,
 'Plan the layout and find images','Say it out loud to check it sounds natural',
 'Research, outline and write a full draft','Imagine yourself on stage and rehearse','expression','en'),
('Which feedback helps you improve most?',NULL,
 'Errors highlighted visually with colors','Being told which word or tone sounded wrong',
 'A detailed written explanation','A corrected scenario to re-practice','feedback','en'),
('Lost abroad and need directions — how do you prepare?',NULL,
 'Pull up a map and plan visually','Mentally rehearse what you''ll say',
 'Look up the exact phrase and read it','Just walk up and try, using gestures','scenario','en'),
('Which English class would you enjoy most?',NULL,
 'Rich slides, videos and visuals','Dynamic explanations with lots of Q&A',
 'Handouts, readings and whiteboard notes','Group activities and role-plays','learning environment','en'),
('To speak up in English meetings, how do you practice?',NULL,
 'Watch real meeting videos','Practice spontaneous dialogue with a partner',
 'Read a guide on contributing in meetings','Join a simulated meeting and do it','workplace','en'),
('When do you feel most accomplished learning English?',NULL,
 'Understanding a video without subtitles','Having a smooth conversation with a foreigner',
 'Reading a full article and understanding it','Using English to complete a real task','motivation','en'),
('Which app feature appeals to you most?',NULL,
 'Animated flashcards and visual progress','Real-time voice chat with an AI',
 'Detailed grammar notes and explanations','Mission challenges and achievements','tool preference','en'),
('Learning a new accent, what is most effective?',NULL,
 'Watch the speaker''s mouth movements','Shadow audio repeatedly and listen back',
 'Read phonetic rules and guides','Imitate it in real conversations','pronunciation','en'),
('How do you prefer to see your progress?',NULL,
 'A visual dashboard with charts','A voice summary of your week',
 'A detailed written strengths report','A list of tasks you''ve completed','feedback','en'),
('If you could review this week one way, which?',NULL,
 'Flip through flashcards and images','Re-listen to conversation recordings',
 'Re-read your notes and transcripts','Redo a similar scenario from scratch','review','en');

-- 確認
SELECT language, COUNT(*) AS total FROM public.vark_questions GROUP BY language;
